title = "Happy Birthday %s ğŸ‰ğŸ‚ğŸˆğŸğŸŠğŸ¥³"

[smtp]
host = "smtp.example.com"
port = 587
user = "mail@example.com"
pass = "CHANGE_ME"

[imgflip]
text = "Happy Birthday!"
user = "example"
pass = "CHANGE_ME"
ids = [
    11797874,
    31643391,
    49197432,
    33780549,
    104027179,
    133159853,
    139525770,
    89443319,
    96276715,
    132150729,
    30619095,
    39603126,
    169117868,
    7862568,
    1570716,
    45992191,
    32534633,
    24883880,
    160959359,
    275921363,
    344391507,
    191409477,
    503981719
]